version: '3.8'
services:
  api:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
  db:
    image: mysql
    command: --init-file /docker-entrypoint-initdb.d/setup.sql
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
    ports:
      - "${DATABASE_PORT}:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - "${PHP_MY_ADMIN_PORT}:80"
